# Generated by Django 4.0.3 on 2022-05-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('checking_account', models.CharField(max_length=32, null=True)),
                ('ASE_certified', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('cost', models.FloatField(default=24.99)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=16)),
                ('lname', models.CharField(default='', max_length=32)),
                ('address', models.CharField(default='', max_length=64)),
                ('user_type', models.CharField(default='C', max_length=1)),
                ('DOB', models.DateField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(default='', max_length=32)),
                ('model', models.CharField(default='', max_length=32)),
                ('year', models.IntegerField(default=2022)),
                ('last_oil_change', models.DateField()),
                ('last_state_inspection', models.DateField()),
                ('registration_number', models.IntegerField(default=1)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
                ('rating', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mechanic')),
            ],
        ),
        migrations.AddField(
            model_name='mechanic',
            name='u_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('1', 'In Progress'), ('2', 'Complete')], default='In Progress', max_length=16)),
                ('mechanic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mechanic')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobrequests')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequests',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services'),
        ),
        migrations.AddField(
            model_name='jobrequests',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
