# Generated by Django 4.0.3 on 2022-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='checking_account',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
