# Generated by Django 4.0.3 on 2022-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(default='Show description', max_length=140),
            preserve_default=False,
        ),
    ]
