# Generated by Django 4.0.3 on 2022-04-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mechanic_checking_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='rating',
        ),
    ]
